"""Data quality checks -> reports/data_quality.md

Four classic data-quality dimensions:
  COMPLETENESS          - are required values present?        (% non-null)
  UNIQUENESS            - is the key really unique?           (duplicate count)
  VALIDITY              - do values follow the rules/format?  (bad-row count)
  REFERENTIAL INTEGRITY - does every foreign key find its parent? (orphan count)
In production you would express these in Great Expectations / Deequ / dbt tests
and fail the pipeline (or alert) when a check fails.
"""
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ROOT, banner, get_spark  # noqa: E402


def completeness(spark, table, column, threshold=0.98):
    r = spark.sql(f"SELECT count(*) n, count({column}) filled FROM {table}").first()
    pct = r.filled / r.n if r.n else 0
    return ("Completeness", table, f"{column} not null", f"{pct:.2%}", f">= {threshold:.0%}", pct >= threshold)


def uniqueness(spark, table, key, where="true"):
    r = spark.sql(f"SELECT count(*) n, count(DISTINCT {key}) d FROM {table} WHERE {where}").first()
    dups = r.n - r.d
    label = f"{key} unique" + ("" if where == "true" else f" ({where})")
    return ("Uniqueness", table, label, f"{dups} duplicates", "0", dups == 0)


def validity(spark, table, rule_sql, description):
    bad = spark.sql(f"SELECT count(*) c FROM {table} WHERE NOT ({rule_sql})").first().c
    return ("Validity", table, description, f"{bad} invalid rows", "0", bad == 0)


def ref_integrity(spark, child, fk, parent, pk):
    orphans = spark.sql(f"""SELECT count(*) c FROM {child} c LEFT JOIN {parent} p ON c.{fk} = p.{pk}
                            WHERE p.{pk} IS NULL""").first().c
    return ("Referential integrity", child, f"{fk} -> {parent}.{pk}", f"{orphans} orphans", "0", orphans == 0)


def run_checks(spark):
    return [
        completeness(spark, "silver.customers", "email_hash"),
        completeness(spark, "silver.customers", "phone_masked"),
        completeness(spark, "silver.orders", "order_ts", 1.0),
        completeness(spark, "gold.fact_sales", "customer_sk", 1.0),
        uniqueness(spark, "silver.customers", "customer_id"),
        uniqueness(spark, "silver.orders", "order_id"),
        uniqueness(spark, "gold.fact_sales", "order_item_id"),
        uniqueness(spark, "gold.dim_customer", "customer_sk"),
        uniqueness(spark, "gold.dim_customer", "customer_id", "is_current"),
        validity(spark, "gold.fact_sales", "quantity > 0", "quantity > 0"),
        validity(spark, "gold.fact_sales", "net_amount >= 0 AND net_amount <= gross_amount",
                 "0 <= net_amount <= gross_amount"),
        validity(spark, "silver.orders", "order_ts BETWEEN TIMESTAMP'2015-01-01' AND current_timestamp()",
                 "order_ts between 2015 and now"),
        validity(spark, "silver.customers", "email_hash IS NULL OR email_hash RLIKE '^[0-9a-f]{64}$'",
                 "email is a SHA-256 hash (no raw email)"),
        validity(spark, "silver.customers", "phone_masked IS NULL OR phone_masked RLIKE '^XXXXXX[0-9]{4}$'",
                 "phone masked to last 4 digits"),
        validity(spark, "silver.stores", "region IN ('NORTH','SOUTH','EAST','WEST')", "region in allowed list"),
        validity(spark, "silver.stores", "city = initcap(lower(trim(city)))", "city in standard Title Case"),
        validity(spark, "gold.dim_customer", "effective_from < effective_to", "SCD2 window is valid"),
        ref_integrity(spark, "gold.fact_sales", "date_key", "gold.dim_date", "date_key"),
        ref_integrity(spark, "gold.fact_sales", "customer_sk", "gold.dim_customer", "customer_sk"),
        ref_integrity(spark, "gold.fact_sales", "product_key", "gold.dim_product", "product_key"),
        ref_integrity(spark, "gold.fact_sales", "store_key", "gold.dim_store", "store_key"),
    ]


def write_report(results, quarantine, silver_stats):
    passed = sum(r[-1] for r in results)
    lines = [
        "# Data quality report", "",
        f"_Generated by `src/quality_checks.py` on {datetime.now():%Y-%m-%d %H:%M}_", "",
        f"**{passed}/{len(results)} checks passed.**", "",
        "| # | Dimension | Table | Check | Measured | Expected | Result |",
        "|---|---|---|---|---|---|---|",
    ]
    for i, (dim, table, check, measured, expected, ok) in enumerate(results, 1):
        lines.append(f"| {i} | {dim} | `{table}` | {check} | {measured} | {expected} | {'PASS' if ok else 'FAIL'} |")
    lines += ["", "## Bronze -> Silver row flow", "",
              "| Table | Bronze rows (all versions) | Duplicates / old CDC versions removed | Silver rows | Quarantined |",
              "|---|---|---|---|---|"]
    for t, s in silver_stats.items():
        lines.append(f"| {t} | {s['bronze_rows']:,} | {s['duplicates_or_old_versions_removed']:,} | "
                     f"{s['silver_rows']:,} | {s['quarantined_rows']:,} |")
    lines += ["", "## Quarantine (rows held back, not deleted)", "",
              "Bad rows are kept in `lake/quarantine/<table>/` with a `_reject_reason` so they can be fixed "
              "at the source and replayed.", "", "| Table | Reason | Rows |", "|---|---|---|"]
    for t, reason, n in quarantine:
        lines.append(f"| {t} | {reason} | {n:,} |")
    lines += ["", "Note: `silver.customers.email_hash` completeness is below 100% because ~1% of legacy "
              "customers never had an email. They are kept (a customer without email is still a valid "
              "customer) and the gap is reported here instead."]
    out = ROOT / "reports" / "data_quality.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    return passed


if __name__ == "__main__":
    spark = get_spark("quality_checks")
    banner("Data quality checks")
    results = run_checks(spark)
    for dim, table, check, measured, expected, ok in results:
        print(f"  {'PASS' if ok else 'FAIL'}  {dim:<22} {table:<20} {check:<40} {measured}")
    quarantine = []
    for t in ["customers", "products", "stores", "orders", "order_items"]:
        df = spark.read.format("delta").load(str(ROOT / "lake" / "quarantine" / t))
        for r in df.groupBy("_reject_reason").count().orderBy("count", ascending=False).collect():
            quarantine.append((t, r["_reject_reason"], r["count"]))
    stats = json.loads((ROOT / "lake" / "_state" / "silver_stats.json").read_text())
    passed = write_report(results, quarantine, stats)
    print(f"\n  {passed}/{len(results)} checks passed -> reports/data_quality.md")
    spark.stop()
